<table width="100%" cellspacing="3" cellpadding="3" border="0">
	<tr><td nowrap class="title"><b>Administration</b></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_manageeth.cgi">Manage ethernet</a></td></tr>
	<tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_passwd.cgi">Change password</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_backrest.cgi">Backup/Restore</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_rtc.cgi">Set real time clock</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_remote.cgi">Remote access</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_unitname.cgi">Unit name</a></td></tr>
	<tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_pingtest.cgi">Ping test</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_syslog.cgi">System log</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_startup.cgi">Startup script</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_shutdown.cgi">Shutdown script</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_ipup.cgi">IP-Up script</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_ipdown.cgi">IP-Down script</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_usercron.cgi">User crontab</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_upload.cgi">Upload file</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_sendsms.cgi">Send SMS</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_unlock.cgi">Disable PIN</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_report.cgi">Send report</a></td></tr>
	<tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_update.cgi">Update firmware</a></td></tr>
	<tr><td nowrap class="menu">&nbsp;&nbsp;<a href="admin_reboot.cgi">Reboot</a></td></tr>
</table>
