<table width="100%" cellspacing="3" cellpadding="3" border="0">
    <tr><td nowrap class="title"><b>Configuration</b></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_ppp.cgi">Internet</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_eth.cgi">LAN</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_wifi.cgi">WiFi</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_nat.cgi">Port forwarding</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_static.cgi">Static routes</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_vrrp.cgi">VRRP</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_firewall.cgi">Firewall</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_snmp.cgi">SNMP</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_gre.cgi">GRE</a></td></tr><!-- config_gren.cgi -->
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_gpio.cgi">GPIO</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_openvpn.cgi">OpenVPN tunnel</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_ovpnserv.cgi">OpenVPN server</a></td></tr><!-- config_ovpnservn.cgi -->
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_ipsec.cgi">IPsec</a></td></tr><!-- config_ipsecn.cgi -->
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_l2tp.cgi">L2TP</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_pptp.cgi">PPTP client</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_serial.cgi">Serial port</a></td></tr> 
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_dyndns.cgi">DynDNS</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_ntp.cgi">NTP</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_sms.cgi">SMS</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="config_dreboot.cgi">Daily reboot</a></td></tr>
</table>
