<table width="100%" cellspacing="3" cellpadding="3" border="0">
    <tr><td nowrap class="title"><b>Status and log</b></td></tr>
	<tr><td nowrap class="menu">&nbsp;&nbsp;<a href="status_ppp.cgi">Internet</a></td></tr>
	<tr><td nowrap class="menu">&nbsp;&nbsp;<a href="status_eth.cgi">LAN</a></td></tr>
	<tr><td nowrap class="menu">&nbsp;&nbsp;<a href="status_dhcp.cgi">DHCP</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="status_iptables.cgi">Iptables</a></td></tr>
	<tr><td nowrap class="menu">&nbsp;&nbsp;<a href="status_openvpn.cgi">OpenVPN tunnel</a></td></tr>
    <tr><td nowrap class="menu">&nbsp;&nbsp;<a href="status_ovpnserv.cgi">OpenVPN server</a></td></tr>
	<tr><td nowrap class="menu">&nbsp;&nbsp;<a href="status_ipsec.cgi">IPsec</a></td></tr>
	<tr><td nowrap class="menu">&nbsp;&nbsp;<a href="status_dyndns.cgi">DynDNS</a></td></tr>
	<tr><td nowrap class="menu">&nbsp;&nbsp;<a href="status_syslog.cgi">System log</a></td></tr>
</table>
