#!/bin/sh

stop() {
    echo -n "Stopping crond: "
    killall -9 crond
    RETVAL=$?
    if [ "$RETVAL" = "0" ]; then
        echo "done"
    else
        echo "failed"
    fi
}

case "$1" in
    start|stop|restart)
        stop 
        exit $RETVAL
    ;;
    *)
        echo "Usage: $0 {start|restart|stop}"
        exit 1
    ;;
esac

