#!/bin/sh
#
# $Id: dhcp3-server.init.d,v 1.4 2003/07/13 19:12:41 mdz Exp $
#
# On what interfaces should the DHCP server (dhcpd) serve DHCP requests?
#       Separate multiple interfaces with spaces, e.g. "eth0 eth1".

[ -e /mnt/rwfs/settings/settings.eth ] && . /mnt/rwfs/settings/settings.eth
[ -e /mnt/rwfs/settings/settings.wifi ] && . /mnt/rwfs/settings/settings.wifi

INTERFACES=""

if [ ! -z "$WIFI_MODE" ] && [ "$WIFI_MODE" = "AUTO" ]; then
    if [ -f /var/tmp/wifi-mode ]; then
        CURRENT_WIFI_MODE=$(cat /var/tmp/wifi-mode)
    else
        CURRENT_WIFI_MODE=AP
        echo -n AP > /var/tmp/wifi-mode
    fi
else
    CURRENT_WIFI_MODE=$WIFI_MODE
fi

if [ "$ETH_DHCP_ENABLED" = "0" ] && [ "$WIFI_DHCP_ENABLED" = "0"]; then
    echo "Skipped"
    exit 0
fi

if [ "$ETH_DHCP_ENABLED" = "1" ]; then
    INTERFACES=$INTERFACES" eth0"
fi

if [ "$WIFI_DHCP_ENABLED" = "1" ] && [ "$CURRENT_WIFI_MODE" = "AP" ]; then
    INTERFACES=$INTERFACES" wlan0"
fi

INTERFACES=$(echo $INTERFACES | awk '{$1=$1};1') # trim leading and trailing spaces

test -x /usr/sbin/dhcpd || exit 0
case "$1" in
    start)
        echo -n "Starting DHCP server: "
        if [ ! -f /etc/dhcpd.conf ]; then
            echo "Skipped"
            exit 0
        fi
        test -d /var/lib/dhcp/ || mkdir -p /var/lib/dhcp/
        test -f /var/lib/dhcp/dhcpd.leases || touch /var/lib/dhcp/dhcpd.leases  
        start-stop-daemon -q -S -x /usr/sbin/dhcpd -- -q $INTERFACES
        if [ "$?" = "0" ]; then
            echo "Done"
        else
            echo "Failed"
        fi
        ;;
    stop)
        echo -n "Stopping DHCP server: "
        start-stop-daemon -q -K -x /usr/sbin/dhcpd
        echo "Done"
        ;;
    restart | force-reload)
        $0 stop
        sleep 2
        $0 start
        if [ "$?" != "0" ]; then
            exit 1
        fi
        ;;
    *)
        echo "Usage: /etc/init.d/dhcp-server {start|stop|restart|force-reload}"
        exit 1 
esac

exit 0
