#!/bin/sh
#
# Starts dropbear sshd.
#

# Make sure the dropbearkey progam exists and executable
[ -x /usr/bin/dropbearkey ] || exit 0

if [ -e /mnt/rwfs/settings/settings.remote ]; then
    . /mnt/rwfs/settings/settings.remote
else 
    . /etc/defaults/settings.remote
fi

start() {
    if [ "$REMOTE_SSH" != "1" ]; then
        exit 0
    fi
    
    [ "$REMOTE_SSH_PORT" == "" ] && REMOTE_SSH_PORT=22
    
    echo -n "Starting dropbear sshd: "
    # Make sure dropbear directory exists
    if [ ! -d /etc/dropbear ] ; then
        mkdir -p /etc/dropbear
    fi
    # Check for the Dropbear RSA key
    if [ ! -f /etc/dropbear/dropbear_rsa_host_key ] ; then
        echo "generating rsa key... "
        /usr/bin/dropbearkey -t rsa -f /mnt/rwfs/etc/dropbear/dropbear_rsa_host_key > /dev/null 2>&1
    fi

    # Check for the Dropbear DSS key
    if [ ! -f /etc/dropbear/dropbear_dss_host_key ] ; then
        echo "generating dsa key...  "
        /usr/bin/dropbearkey -t dss -f /mnt/rwfs/etc/dropbear/dropbear_dss_host_key > /dev/null 2>&1
    fi
    umask 077
    start-stop-daemon -S -q -p /var/run/dropbear.pid --exec /usr/sbin/dropbear -- -b /etc/issue.net -p $REMOTE_SSH_PORT
    echo "OK"
}
stop() {
    echo -n "Stopping dropbear sshd: "
    start-stop-daemon -K -q -p /var/run/dropbear.pid
    echo "OK"
}
restart() {
    stop
    start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

