#!/bin/sh

if [ -e /mnt/rwfs/settings/settings.remote ]; then
    . /mnt/rwfs/settings/settings.remote
else 
    . /etc/defaults/settings.remote
fi

start(){
        echo -n "Starting telnetd: "
        
        if [ "$REMOTE_TELNET" != "1" ]; then
        echo "skipped"
        exit 0
        fi
        
        [ "$REMOTE_TELNET_PORT" == "" ] && REMOTE_TELNET_PORT=23
        
        telnetd -p $REMOTE_TELNET_PORT
        
        RET=$?
        if [ "$RET" = "0" ]; then 
            echo "done" 
        else 
            echo "failed"
        fi
}

stop(){
        echo -n "Stopping telnetd: "
        kill `ps|grep telnetd|grep -v grep|grep -v init.d|awk '{print $1}'` > /dev/null
        RET=$?
        if [ "$RET" = "0" ]; then 
                echo "done" 
        else 
                echo "failed"
        fi  
}

case "$1" in
    start)    
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
